# Generated by Django 6.0.4 on 2026-04-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inheritablediseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'inheritablediseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measurementtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'measurementtypes',
                'managed': False,
            },
        ),
    ]
